name: Kernel + Magisk Module Builder

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3
        mkdir -p AnyKernel3/modules

    - name: Create Magisk Module Structure
      run: |
        MODULE_DIR="AnyKernel3/modules/kernel_enable"
        mkdir -p "$MODULE_DIR"

        # module.prop
        cat > "$MODULE_DIR/module.prop" << 'EOF'
id=kernel_enable
name=Kernel_optimization
version=1.2
versionCode=12
author=xx
description=✅ Enables kernel optimization
EOF

        # post-fs-data.sh
        cat > "$MODULE_DIR/post-fs-data.sh" << 'EOF'
#!/system/bin/sh

# Improve Mem TCP
sysctl -w net.ipv4.tcp_rmem='524288 1048576 2097152'
sysctl -w net.ipv4.tcp_wmem='524288 1048576 2097152'
sysctl -w net.ipv6.tcp_rmem='524288 1048576 2097152'
sysctl -w net.ipv6.tcp_wmem='524288 1048576 2097152'

# Reduce TCP latency
sysctl -w net.ipv4.tcp_slow_start_after_idle=0
sysctl -w net.ipv4.tcp_no_metrics_save=1
sysctl -w net.ipv4.tcp_mtu_probing=1

resetprop ro.boot.vbmeta.invalidate_on_error yes
EOF

        # Property files
        declare -A PROPS=(
          ["persist.prop"]='# persist debug
persist.sys.assert.state=false
persist.sys.alwayson.enable=false
persist.sys.debug.layer_trace.enable=false
persist.sys.oplus.perfrecord=false
persist.sys.oplus_trace=0
persist.sys.oplus.theia_screen_monitor.disabled=1
persist.sys.oplus.ostats.labmode.enable=0
persist.sys.oplus.cvt.manager=0
persist.sys.ostatsd.enable=0
persist.sys.ostats_tpd.enable=0
persist.sys.ostats_pullerd.enable=0
persist.sys.ood.enable=0
persist.sys.midasd.enable=0
persist.vendor.ims.disableDebugLogs=1
persist.vendor.ims.disableIMSLogs=1
persist.vendor.ims.disableQXDMLogs=1'

          ["qcom.prop"]='# Disable CoreSight
persist.debug.coresight.config=

# QCOM Configuration
dalvik.vm.isa.arm64.features=runtime
dalvik.vm.isa.arm64.variant=oryon
ro.bionic.cpu_variant=oryon
persist.logd.diag.tcpdump=false
persist.sys.qseelogd=false
persist.sys.ssr.enable_debug=false
vendor.bluetooth.startbtlogger=false
vendor.chre.enabled=true
vendor.pasr.enabled=true'

          ["oplus.prop"]='## Oneplus Optimizations
debug.sf.oplus_display_trace.enable=false
debug.vendor.perf.smart_touch.trace=false
persist.sys.oplus.need_log=false
# ... (include full oplus.prop content) ...'

          ["system.prop"]='# BBR Configuration
net.ipv4.tcp_congestion_control=bbr
net.core.default_qdisc=fq
# ... (include full system.prop content) ...'
        )

        for prop in "${!PROPS[@]}"; do
          echo "${PROPS[$prop]}" > "$MODULE_DIR/$prop"
        done

        chmod +x "$MODULE_DIR/post-fs-data.sh"
        echo "Magisk module structure created"

    - name: Package Kernel+Module
      run: |
        cd AnyKernel3
        ZIP_NAME="Kernel-${GITHUB_SHA:0:7}-$(date +%Y%m%d).zip"
        
        # Add AK3 files
        cp ../Image.gz-dtb .
        cp ../dtbo.img .
        
        # Fengchi Patch handling
        if [ "${{ inputs.model }}" == "OPAce5Pro" ]; then
          mkdir dtbo_extract
          split-appended-dtbo dtbo.img --out dtbo_extract
          sed -i 's/hmbird/xxbird/g' dtbo_extract/*.dtbo
          mkdtboimg -o dtbo.img dtbo_extract/*.dtbo
          ZIP_NAME="${ZIP_NAME%.zip}-CN.zip"
        fi
        
        zip -r9 "../$ZIP_NAME" .
        echo "Created ZIP: $ZIP_NAME"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-Package
        path: |
          *.zip
          !*.tar.gz

    - name: Cleanup
      run: |
        rm -rf AnyKernel3
        rm -f Image.gz-dtb dtbo.img
